// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Movable, MovableTableId } from "./tables/Movable.sol";
import { NonPlayer, NonPlayerTableId } from "./tables/NonPlayer.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { Parsed, ParsedTableId } from "./tables/Parsed.sol";
import { Players, PlayersData, PlayersTableId } from "./tables/Players.sol";
