// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICharacterSystem {
  function addCharacter(string memory name, string memory level) external;

  function isParsed(bytes32 playerId) external;
}
